datoscentrosvotacion:
    path:     /
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:index" }

datoscentrosvotacion_list:
    path:     /{id}/list
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:index" }
    
datoscentrosvotacion_show:
    path:     /{id}/show
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:show" }

datoscentrosvotacion_new:
    path:     /new
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:new" }

datoscentrosvotacion_create:
    path:     /create
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:create" }
    requirements: { _method: post }

datoscentrosvotacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:edit" }

datoscentrosvotacion_update:
    path:     /{id}/update
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:update" }
    requirements: { _method: post|put }

datoscentrosvotacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:delete" }
    requirements: { _method: post|delete }

datoscentrosvotacion_cantidad:
    path:     /{id}/cantidad
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:cantidad" }

datoscentrosvotacion_createcant:
    path:     /createcant
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:createcant" }
    requirements: { _method: post }
    
datoscentrosvotacion_asignarpersona:
    path:     /asignarpersona
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:asignarpersona" }
    requirements: { _method: post|get }

datoscentrosvotacion_verpersona:
    path:     /{id}/verpersona
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:verpersona" }
    requirements: { _method: post|get }
    
datoscentrosvotacion_verasignaciones:
    path:     /{id}/verasignaciones/{porcv}
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:verasignaciones", porcv: 0  }
    requirements: { _method: post|get }    
    
datoscentrosvotacion_borrarpersona:
    path:     /{id}/borrarpersona
    defaults: { _controller: "VictoriaAppBundle:DatosCentrosVotacion:borrarpersona" }
    requirements: { _method: get|post|delete }    
