datospublicidadmedios:
    path:     /
    defaults: { _controller: "VictoriaAppBundle:DatosPublicidadMedios:index" }

datospublicidadmedios_show:
    path:     /{id}/show
    defaults: { _controller: "VictoriaAppBundle:DatosPublicidadMedios:show" }

datospublicidadmedios_new:
    path:     /new
    defaults: { _controller: "VictoriaAppBundle:DatosPublicidadMedios:new" }

datospublicidadmedios_create:
    path:     /create
    defaults: { _controller: "VictoriaAppBundle:DatosPublicidadMedios:create" }
    requirements: { _method: post }

datospublicidadmedios_edit:
    path:     /{id}/edit
    defaults: { _controller: "VictoriaAppBundle:DatosPublicidadMedios:edit" }

datospublicidadmedios_update:
    path:     /{id}/update
    defaults: { _controller: "VictoriaAppBundle:DatosPublicidadMedios:update" }
    requirements: { _method: post|put }

datospublicidadmedios_delete:
    path:     /{id}/delete
    defaults: { _controller: "VictoriaAppBundle:DatosPublicidadMedios:delete" }
    requirements: { _method: post|delete }
