datosdistritos:
    path:     /
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:index" }
    
datosdistritos_list:
    path:     /{id}/list
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:index" }

datosdistritos_show:
    path:     /{id}/show
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:show" }

datosdistritos_new:
    path:     /new
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:new" }

datosdistritos_create:
    path:     /create
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:create" }
    requirements: { _method: post }

datosdistritos_edit:
    path:     /{id}/edit
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:edit" }

datosdistritos_update:
    path:     /{id}/update
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:update" }
    requirements: { _method: post|put }

datosdistritos_delete:
    path:     /{id}/delete
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:delete" }
    requirements: { _method: post|delete }

datosdistritos_cantidad:
    path:     /{id}/cantidad
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:cantidad" }

datosdistritos_createcant:
    path:     /createcant
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:createcant" }
    requirements: { _method: post }
    
datosdistritos_asignarpersona:
    path:     /asignarpersona
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:asignarpersona" }
    requirements: { _method: post|get }

datosdistritos_verpersona:
    path:     /{id}/verpersona
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:verpersona" }
    requirements: { _method: post|get }
    
datosdistritos_verasignaciones:
    path:     /{id}/verasignaciones
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:verasignaciones" }
    requirements: { _method: post|get }    
    
datosdistritos_borrarpersona:
    path:     /{id}/borrarpersona
    defaults: { _controller: "VictoriaAppBundle:DatosDistritos:borrarpersona" }
    requirements: { _method: get|post|delete }   