datoscomentariospresupuesto:
    path:     /
    defaults: { _controller: "VictoriaAppBundle:DatosComentariosPresupuesto:index" }

datoscomentariospresupuesto_show:
    path:     /{id}/show
    defaults: { _controller: "VictoriaAppBundle:DatosComentariosPresupuesto:show" }

datoscomentariospresupuesto_new:
    path:     /new
    defaults: { _controller: "VictoriaAppBundle:DatosComentariosPresupuesto:new" }

datoscomentariospresupuesto_create:
    path:     /create
    defaults: { _controller: "VictoriaAppBundle:DatosComentariosPresupuesto:create" }
    requirements: { _method: post }

datoscomentariospresupuesto_edit:
    path:     /{id}/edit
    defaults: { _controller: "VictoriaAppBundle:DatosComentariosPresupuesto:edit" }

datoscomentariospresupuesto_update:
    path:     /{id}/update
    defaults: { _controller: "VictoriaAppBundle:DatosComentariosPresupuesto:update" }
    requirements: { _method: post|put }

datoscomentariospresupuesto_delete:
    path:     /{id}/delete
    defaults: { _controller: "VictoriaAppBundle:DatosComentariosPresupuesto:delete" }
    requirements: { _method: post|delete|get }
