datosaportaciones:
    path:     /
    defaults: { _controller: "VictoriaAppBundle:DatosAportaciones:index" }

datosaportaciones_show:
    path:     /{id}/show
    defaults: { _controller: "VictoriaAppBundle:DatosAportaciones:show" }

datosaportaciones_new:
    path:     /new
    defaults: { _controller: "VictoriaAppBundle:DatosAportaciones:new" }

datosaportaciones_create:
    path:     /create
    defaults: { _controller: "VictoriaAppBundle:DatosAportaciones:create" }
    requirements: { _method: post }

datosaportaciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "VictoriaAppBundle:DatosAportaciones:edit" }

datosaportaciones_update:
    path:     /{id}/update
    defaults: { _controller: "VictoriaAppBundle:DatosAportaciones:update" }
    requirements: { _method: post|put }

datosaportaciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "VictoriaAppBundle:DatosAportaciones:delete" }
    requirements: { _method: post|delete }
