datoseventos:
    path:     /
    defaults: { _controller: "VictoriaAppBundle:DatosEventos:index" }

datoseventos_show:
    path:     /{id}/show
    defaults: { _controller: "VictoriaAppBundle:DatosEventos:show" }

datoseventos_new:
    path:     /new
    defaults: { _controller: "VictoriaAppBundle:DatosEventos:new" }

datoseventos_create:
    path:     /create
    defaults: { _controller: "VictoriaAppBundle:DatosEventos:create" }
    requirements: { _method: post }

datoseventos_edit:
    path:     /{id}/edit
    defaults: { _controller: "VictoriaAppBundle:DatosEventos:edit" }

datoseventos_update:
    path:     /{id}/update
    defaults: { _controller: "VictoriaAppBundle:DatosEventos:update" }
    requirements: { _method: post|put }

datoseventos_delete:
    path:     /{id}/delete
    defaults: { _controller: "VictoriaAppBundle:DatosEventos:delete" }
    requirements: { _method: post|delete }
