datosrespuestascuestionario:
    path:     /
    defaults: { _controller: "VictoriaAppBundle:DatosRespuestasCuestionario:index" }

datosrespuestascuestionario_show:
    path:     /{id}/show
    defaults: { _controller: "VictoriaAppBundle:DatosRespuestasCuestionario:show" }

datosrespuestascuestionario_new:
    path:     /new
    defaults: { _controller: "VictoriaAppBundle:DatosRespuestasCuestionario:new" }

datosrespuestascuestionario_create:
    path:     /create
    defaults: { _controller: "VictoriaAppBundle:DatosRespuestasCuestionario:create" }
    requirements: { _method: post }

datosrespuestascuestionario_edit:
    path:     /{id}/edit
    defaults: { _controller: "VictoriaAppBundle:DatosRespuestasCuestionario:edit" }

datosrespuestascuestionario_update:
    path:     /{id}/update
    defaults: { _controller: "VictoriaAppBundle:DatosRespuestasCuestionario:update" }
    requirements: { _method: post|put }

datosrespuestascuestionario_delete:
    path:     /{id}/delete
    defaults: { _controller: "VictoriaAppBundle:DatosRespuestasCuestionario:delete" }
    requirements: { _method: post|delete }
