datoslistapresupuesto_solo:
    path:     /
    
datoslistapresupuesto_list:
    path:     /{id}/list
    defaults: { _controller: "VictoriaAppBundle:DatosListaPresupuesto:index" }

datoslistapresupuesto_show:
    path:     /{id}/show
    defaults: { _controller: "VictoriaAppBundle:DatosListaPresupuesto:show" }

datoslistapresupuesto_new:
    path:     /new
    defaults: { _controller: "VictoriaAppBundle:DatosListaPresupuesto:new" }

datoslistapresupuesto_create:
    path:     /create
    defaults: { _controller: "VictoriaAppBundle:DatosListaPresupuesto:create" }
    requirements: { _method: post }

datoslistapresupuesto_edit:
    path:     /{id}/edit
    defaults: { _controller: "VictoriaAppBundle:DatosListaPresupuesto:edit" }

datoslistapresupuesto_update:
    path:     /{id}/update
    defaults: { _controller: "VictoriaAppBundle:DatosListaPresupuesto:update" }
    requirements: { _method: post|put }

datoslistapresupuesto_delete:
    path:     /{id}/delete
    defaults: { _controller: "VictoriaAppBundle:DatosListaPresupuesto:delete" }
    requirements: { _method: post|delete|get }
