services:
#    victoria_app.example:
#        class: Victoria\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    victoria_app.vicseguridad:
        class: Victoria\AppBundle\Controller\Seguridad
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
